name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
      - name: Test with Gradle
        run: ./gradlew test
      - name: Build with Gradle
        run: ./gradlew jar
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: randomHide.jar
          path: build/libs/randomHide-1.0.0.jar